.github/workflows/cleanup.yml

| Issue         | #33..
| Type          | <ul><li>- [ ] Feat</li><li>- [ ] Hotfix</li><li>- [ ] Doc</li><li>- [ ] Refacto</li></ul>

Fix cleanup

---

.github/workflows/cleanup.yml

| Issue         | #33..
| Type          | <ul><li>- [ ] Feat</li><li>- [ ] Hotfix</li><li>- [ ] Doc</li><li>- [ ] Refacto</li></ul>

Fix deleting pvc on cleanup

---

.github/workflows/ci.yml
pwa/pages/liste-des-reparateurs.tsx

Remove useless get static props
| Issue         |  #19 
| Type          | <ul><li>- [ ] Feat</li><li>- [ ] Hotfix</li><li>- [ ] Doc</li><li>- [x] Refacto</li></ul>

repairer page slow

---

api/src/Repairers/Filter/AroundFilter.php
api/tests/Repairer/Distance/DistanceTest.php
api/tests/Repairer/Filters/AroundFilterTest.php
pwa/components/homepage/SearchARepairer.tsx
pwa/contexts/SearchRepairerContext.tsx
pwa/pages/reparateur/chercher-un-reparateur.tsx

Allow to provide a radius in the aroundfilter, and a select in the pwa
| Issue         | #6 
| Type          | <ul><li>- [x] Feat</li><li>- [ ] Hotfix</li><li>- [ ] Doc</li><li>- [x] Refacto</li></ul>

Allow to filter by radius

---

pwa/components/dashboard/informations/ContactDetails.tsx
pwa/components/homepage/SearchARepairer.tsx
pwa/components/rendez-vous/PinMap.tsx
pwa/pages/reparateur/chercher-un-reparateur.tsx
pwa/pages/reparateur/inscription.tsx
pwa/utils/apiCity.ts

- replace old used filter by a new filter
- fix display bug : streets not showed when take apppointment with "itinérant" repairer
| Issue         | #7
| Type          | <ul><li>- [x] Feat</li><li>- [x] Hotfix</li><li>- [ ] Doc</li><li>- [ ] Refacto</li></ul>

feat: use zipcode/city name filter to search cities

---

api/src/CSV/CsvExporter.php
api/src/Controller/CustomerCsvController.php
api/src/Repository/UserRepository.php
api/tests/Customers/CustomersCsvControllerTest.php
api/tests/Customers/Security/CustomersCsvControllerTestBadBoss.php
pwa/components/dashboard/customers/CustomersList.tsx
pwa/resources/customerResource.ts

Allow repairer to download a CSV file with all customers infos
| Issue         | #12 
| Break changes |  Yes

create a route to generate a CSV with all repairer's customer

---

pwa/pages/reparateur/chercher-un-reparateur.tsx

fix auto search if change radius
| Issue         |
| Type          | <ul><li>- [ ] Feat</li><li>- [X] Hotfix</li><li>- [ ] Doc</li><li>- [ ] Refacto</li></ul>

fix auto search if change radius

---

pwa/components/common/link/Link.tsx
pwa/pages/admin/contact/index.tsx
pwa/pages/index.tsx
pwa/pages/inscription.tsx
pwa/pages/login.tsx
pwa/pages/mentions-legales.tsx
pwa/pages/notre-collectif.tsx
pwa/pages/reinitialiser-mot-de-passe.tsx
pwa/public/robots.txt

Add canonical + exclude robots.txt paths

---

pwa/pages/reparateur/inscription.tsx

add checkbox to accept chart in repairer registration form
| Issue         | #14 

Feat: add checkbox to accept chart in repairer registration form

---

pwa/components/dashboard/informations/Description.tsx

fix: change label for multi select field for cities in dashboard
| Issue         | 
| Type          | <ul><li>- [ ] Feat</li><li>- [x] Hotfix</li><li>- [ ] Doc</li><li>- [ ] Refacto</li></ul>

fix: change label for multi select field for cities in dashboard

---

api/src/Entity/Repairer.php
api/src/Entity/User.php
api/src/Repairers/Dto/ExportRepairerDto.php
api/src/Repairers/State/ExportRepairerCollectionProvider.php
api/src/User/Dto/ExportUserDto.php
api/src/User/StateProvider/ExportUserCollectionProvider.php
api/tests/AbstractTestCase.php
api/tests/Employees/UpdateEmployeeTest.php
api/tests/Repairer/ExportRepairersCsvTest.php
api/tests/Repairer/Slots/SlotsTestCase.php
api/tests/User/ExportUsersCsvTest.php
pwa/__unit__/downloadFileLink.test.ts
pwa/components/admin/repairers/RepairersList.tsx
pwa/components/admin/users/UsersList.tsx
pwa/components/dashboard/customers/CustomersList.tsx
pwa/resources/customerResource.ts
pwa/resources/repairerResource.ts
pwa/resources/userResource.ts
pwa/utils/downloadFileLink.ts

Admin can download csv files of repairers and users from their respective pages
| Issue         | #12 

feat(admin-dashboard): #12 download csv repairers + users

---

pwa/pages/reparateur/chercher-un-reparateur.tsx

Repairer search bar was too low.
| Issue         | #46 
| Type          | <ul><li>- [ ] Feat</li><li>- [ ] Hotfix</li><li>- [ ] Doc</li><li>- [ ] Refacto</li><li>- [x] Fix</li></ul>

fix(repairer search bar): #46 - fix top position

---

pwa/components/dashboard/appointments/AppointmentCreateAddPrestation.tsx
pwa/components/dashboard/appointments/ModalAppointmentCreate.tsx

fix spaces between fields, add a scrollbar on prestation select
| Issue         | #15 ..

Improve appointment creation

---

pwa/components/admin/repairers/RepairersList.tsx
pwa/components/admin/users/UsersList.tsx

Add useCallBack hook to improve performance
| Issue         | #33..

add useCallback

---

.github/workflows/cd.yml
.github/workflows/deploy.yml
api/Dockerfile
helm/chart/templates/configmap.yaml
helm/chart/templates/cronjob.yaml
helm/chart/templates/deployment.yaml
helm/chart/templates/secrets.yaml
helm/chart/values.yml
pwa/pages/reparateur/chercher-un-reparateur.tsx

| Issue         | #71
| Type          | <ul><li>- [ ] Feat</li><li>- [ ] Hotfix</li><li>- [ ] Doc</li><li>- [ ] Refacto</li></ul>

init the new env

---

pwa/pages/reparateur/chercher-un-reparateur.tsx

improve responsive with adaptives fields on repairer search bar
| Issue         | #70 ..
| Break changes |   No

Change input disposal on mobile search fields

---

.github/workflows/build.yml
.github/workflows/deploy.yml
pwa/pages/reparateur/chercher-un-reparateur.tsx
pwa/pages/reparateur/inscription/mon-enseigne.tsx
pwa/resources/AbstractResource.ts

| Issue         | #33..
| Type          | <ul><li>- [ ] Feat</li><li>- [ ] Hotfix</li><li>- [ ] Doc</li><li>- [ ] Refacto</li></ul>

edit next entrypoint

---

pwa/pages/reparateur/[id].tsx
pwa/pages/reparateur/chercher-un-reparateur.tsx
pwa/pages/reparateur/inscription/mon-enseigne.tsx

Disable getStaticProps until the CI is adapted
| Issue         | ..
| Type          | <ul><li>- [ ] Feat</li><li>- [x] Hotfix</li><li>- [ ] Doc</li><li>- [ ] Refacto</li></ul>

fix: disable getStaticProps

---

pwa/components/repairers/RepairerCard.tsx

remove distance info + set orange the next appointment
| Issue         | #83 ..
| Type          | <ul><li>- [ ] Feat</li><li>- [x] Hotfix</li><li>- [ ] Doc</li><li>- [ ] Refacto</li></ul>

fix(repairer card): remove distance info + set orange the next appointment

---

pwa/components/messagerie/CustomerMessagesContent.tsx
pwa/components/messagerie/RepairerMessagesContent.tsx

show identity to message sender
| Issue         | #56 ..

feat(messagerie): show identity to message sender

---

pwa/components/dashboard/appointments/MapPositionUser.tsx

make text more visible when appointment requesting
| Issue         | #100 ..
| Type          | <ul><li>- [ ] Feat</li><li>- [x] Hotfix</li><li>- [ ] Doc</li><li>- [ ] Refacto</li></ul>

fix: make text more visible when appointment requesting

---

api/src/Emails/NewAppointmentEmail.php
api/src/Notifications/NewAppointmentNotification.php

Change the redirection url after appointment creation
| Issue         | #77 ..

Redirect to the appointment place on the agenda

---

pwa/pages/notre-charte.tsx

Update the rustine libre charter
| Issue         | #88 ..
| Break changes |   No

Add new version of the charter

---

api/migrations/Version20240930143106.php
api/src/Entity/Appointment.php
api/tests/Appointments/Security/PostTest.php
api/tests/Employees/RetrieveEmployeesTest.php
pwa/components/admin/parameters/ParametersHomepagePicture.tsx
pwa/components/dashboard/agenda/ModalShowAppointment.tsx
pwa/components/dashboard/appointments/ModalAppointmentCreate.tsx
pwa/components/homepage/SearchARepairer.tsx
pwa/interfaces/Appointment.ts

Add a phone number for customer without account on appointment creation
| Issue         | #95

fix(appointment): #95 - add customer phone without account

---

pwa/components/dashboard/DashboardLayout.tsx
pwa/components/dashboard/repairers/RepairersList.tsx
pwa/components/sidebar/SidebarListItemRepairers.tsx
pwa/pages/sradmin/dashboard/index.tsx

Add new dabshboardpage, delete list text on mobile, modify /boutiques
| Issue         | #109 ..
| Break changes |   No

Improve responsive on repairer dashboard sidebar

---

api/migrations/Version20240917140317.php
api/src/Appointments/EventSubscriber/SyncGoogleNewAppointmentSubscriber.php
api/src/Controller/SyncGoogleCalendarController.php
api/src/Entity/Repairer.php
pwa/components/calendar/GoogleCalendarSync.tsx
pwa/components/dashboard/agenda/GoogleAgendaLogin.tsx
pwa/contexts/DashboardRepairerContext.tsx
pwa/interfaces/Repairer.ts
pwa/pages/sradmin/boutiques/[repairer_id]/agenda/parametres.tsx

feat: move google calendar login in agenda settings
| Issue         | #108 ..

feat: move google calendar login in agenda settings

---

pwa/components/privacy-policy/ProcessingOfYourData.tsx
pwa/components/privacy-policy/YourRights.tsx

Add google privacy policy and adapt google oauth config
| Issue         | #108 ..

Add privacy policy for google calendar use

---

api/templates/mail/contact.html.twig
helm/chart/values.yml

Modify contact email address and fix contact mail template
| Issue         | #36 ..

update the mailer sender value

---

pwa/components/dashboard/DashboardLayout.tsx
pwa/components/sidebar/SidebarListItem.tsx
pwa/components/sidebar/SidebarListItemRepairers.tsx

Change icon color on navigation according to the path selected
| Issue         | #109 ..

Change icon color on navigation

---

pwa/components/privacy-policy/YourRights.tsx

Add line break
| Issue         | #108 ..

Add style in privacy policy

---

pwa/pages/sradmin/boutiques/[repairer_id]/agenda/parametres.tsx

Wait the google authorization to uncomment it
| Issue         | #108..

Comment the google tab in repairer agenda parameter

---

helm/chart/templates/deployment.yaml
helm/chart/values.yml

Remove useless PVC (replaced by FlySystem+bucket) and update Deployment strategy to RollingUpdate

remove useless pvc and stategy rollingUpdate

---

api/composer.lock
api/src/Emails/NewRepairerEmail.php
api/templates/mail/new_repairer_validated.html.twig
pwa/components/repairers/registration/RegistrationTunnelWorkshop.tsx
pwa/pages/sradmin/boutiques/[repairer_id]/agenda/parametres.tsx

feat: add error message when no street are chosen on repairer register form
| Issue         | https://github.com/coopTilleuls/rustinelibre/issues/1183

feat: add error message when no street are chosen on repairer register form

---

pwa/components/layout/Analytics.tsx

Update tag manager script with latest google documentation code.
| Issue         | #125
| Type          | <ul><li>- [ ] Feat</li><li>- [X] Hotfix</li><li>- [ ] Doc</li><li>- [ ] Refacto</li></ul>

fix: tag manager script from google documentation
